### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by ThatGuyJamal** [Androz2091/discord-invites-tracker#4]
Hello, I was setting up the package using typescript. 

I found an error from index.js
```ts
InvitesTracker.prototype.fetchCache = function () {
        return __awaiter(this, void 0, void 0, function () {
            var fetchGuildCachePromises;
            var _this = this;
            return __generator(this, function (_a) {
                switch (_a.label) {
                    case 0:
                        fetchGuildCachePromises = this.guilds.array().map(function (guild) { return _this.fetchGuildCache(guild); });
                        return [4 /*yield*/, Promise.all(fetchGuildCachePromises)];
                    case 1:
                        _a.sent();
                        return [2 /*return*/];
                }
            });
        });
    };
```
err
```ts
 this.guilds.array is not a function
 ```
Also, there is another error from [here](https://github.com/Androz2091/discord-invites-tracker/blob/master/index.ts#L180)
if the guild does not have a vanity URL then it throws `This guild does not have the VANITY_URL feature enabled.`

**Comment by ririko5834** [comment]
When this will be fixed?

**Comment by ThatGuyJamal** [comment]
> When this will be fixed?

Not sure. Prob not for a while because he has a lot of projects. I found a small workarounds by changing some lines but it's unstable.

**Comment by Pandapip1** [comment]
I opened #5 which should fix this.
