### ISSUE TITLE
Update to v13

### ISSUE THREAD

**Issue by Justman10000** [Androz2091/discord-invites-tracker#7]
Please update to v13! I actually tested it in this version! The bot does not to this react!

**Comment by Justman10000** [comment]
Oh, now he reacts! Now comes this error:

> <bot-path>/node_modules/@androz2091/discord-invites-tracker/lib/index.js:247
>                       fetchGuildCachePromises = this.guilds.array().map(function (guild) { return _this.fetchGuildCache(guild); });
>
> TypeError: this.guilds.array is not a function

**Comment by Pandapip1** [comment]
Fixed by #9
